# Generated by Django 4.2.1 on 2023-05-26 23:30

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=20)),
                ('documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=18)),
                ('cpf', django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True, unique=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparelho', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('observacao', models.TextField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.cliente')),
            ],
        ),
    ]
