# Generated by Django 4.2.1 on 2023-05-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_remove_cliente_cnpj_remove_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacao',
        ),
    ]
