# Generated by Django 4.2.1 on 2023-05-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_remove_cliente_contato_remove_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
